
name: Variable-testing 

on:
 workflow_dispatch 
env:
  cloud: AWS
jobs:
  getting_started:
   runs-on: ubuntu-latest
   env:
    getting: team
   steps: 
    - name: "Hello Cloud"
      run: echo "$getting $First_Name is using $cloud with the project ${{vars.PROJECT_ID}}!"
      env:
        First_Name: JD
  
