
name: Variable-testing 

on:
 workflow_dispatch 
env:
  cloud: AWS
jobs:
  getting_started:
   runs-on: ubuntu-latest
   steps: 
    - name: "checking context variables"
      run: |
       echo "Repository Name : ${{ github.repository }}"
       echo "Workflow Name : ${{ github.workflow }}"
       echo "Triggered by : ${{ github.triggering_actor }}"
      
  
