name: my first flow 

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout rpe
              uses: actions/checkout@v4
              
            - name: List files
              run: ls -ltra

            - name: Executing shell script 
              run: |
               chmod +x script.sh
               ./script.sh
              
              
            
            #- name: List files
            #  run: ls 
            
            #- name: Read File
            # run: cat README.md             