name: my first flow 

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout rpe
              uses: actions/checkout@v4
              
            - name: List files
              run: ls -ltra

             - name: Execute Shell Script
               run: |
                set -e  # Exit immediately if a command exits with a non-zero status
                chmod 400 ascii-shell.sh
                ./ascii-shell.sh
               shell: bash
              
            
            #- name: List files
            #  run: ls 
            
            #- name: Read File
            # run: cat README.md             