name: my first flow 

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout epo
              uses: actions/checkout@v4 
            - name: welcome message
              run: echo "my first github trigger"
            
            - name: List files
              run: list  
            
            - name: Read File
              run: cat README.md             