
name: Variable-testing 

on:
 workflow_dispatch 
env:
  ACTION_STEP_DEBUG: true
jobs:
  getting_started:
   runs-on: ubuntu-latest
   steps: 
    - name: "checking secrets value"
      run: |
       echo "secret value : ${{ secrets.TESTING_KEY }}"
    
