name: CHECKING SECRETS

on:
  push
env: 
  env: dev


jobs:
  getting_started:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checking secrets value"
        run: |
          echo "Secret value: ${{ secrets.CLOUD }}"
    
      
