
name: CHECKING SECRETS

on:
 workflow_dispatch 
env:
    ACTION_STEP_DEBUG: true
jobs:
  getting_started:
    runs-on: ubuntu-latest
    steps: 
     - name: "checking secrets value"
       run: |
        echo "Secret value : ${{ secrets.TESTING_KEY }}"
    
